# Generated by Django 6.1 on 2026-09-01 14:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Turn on when somebody is around to answer. Customers only see the bubble when this is on.', verbose_name='live chat enabled')),
                ('welcome_heading', models.CharField(default='Chat with the salon', help_text='Title at the top of the chat window.', max_length=120)),
                ('welcome_text', models.TextField(default='Ask us anything about services, prices or availability. We usually reply within a few minutes.', help_text='Shown before the customer starts a chat.')),
                ('offline_text', models.TextField(default='Nobody is available to chat right now. Please book online or send us an email.', help_text='Shown instead of the chat form when live chat is switched off but you still want the bubble visible.')),
                ('show_when_offline', models.BooleanField(default=False, help_text='Keep the bubble visible when chat is off, showing the message above instead of hiding entirely.')),
                ('greeting', models.CharField(default='Hi! A stylist has joined the chat. How can we help?', help_text='Sent automatically when a member of staff accepts a chat.', max_length=200)),
                ('busy_text', models.TextField(default='Sorry, we are all with clients at the moment and cannot take the chat. Please try again a little later, or book online.', help_text='Sent automatically when a member of staff declines a chat request.')),
                ('poll_seconds', models.PositiveSmallIntegerField(default=5, help_text='How often an open chat window checks for new messages. Higher = less server load.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(60)])),
                ('require_name', models.BooleanField(default=True, help_text='Ask the customer for a first name before starting the chat.')),
                ('retention_days', models.PositiveIntegerField(default=365, help_text="Conversations untouched for longer than this are deleted by 'manage.py purge_old_chats'.", validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'chat settings',
                'verbose_name_plural': 'chat settings',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('guest_name', models.CharField(blank=True, max_length=80)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('accepted', 'Live'), ('closed', 'Ended'), ('rejected', 'Declined')], default='pending', max_length=10)),
                ('opened_from', models.CharField(blank=True, max_length=255)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_conversations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Salon'), ('system', 'System')], max_length=10)),
                ('sender_name', models.CharField(blank=True, max_length=80)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', '-updated_at'], name='chat_conver_status_7eb480_idx'),
        ),
    ]
