# Generated by Django 6.1 on 2026-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsettings',
            name='follow_business_hours',
            field=models.BooleanField(default=True, help_text='Only offer chat while the salon is open, using the same business hours and vacation entries as the booking calendar. Turn off to offer chat around the clock.'),
        ),
        migrations.AlterField(
            model_name='chatsettings',
            name='enabled',
            field=models.BooleanField(default=False, help_text='The master switch. Off means no chat at all, whatever the opening hours say -- use it when nobody can answer.', verbose_name='live chat switched on'),
        ),
    ]
