# Generated by Django 6.1 on 2026-09-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsettings_follow_business_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsettings',
            name='auto_greeting',
            field=models.CharField(default='Hi {name}, how may I help you?', help_text='Posted automatically the moment a visitor starts a chat, so they can type straight away. Use {name} for the name they gave.', max_length=200),
        ),
        migrations.AlterField(
            model_name='chatsettings',
            name='greeting',
            field=models.CharField(default='{staff} here — I am with you now.', help_text='Posted when a member of staff picks the chat up. Use {staff} for their name.', max_length=200),
        ),
    ]
