# Generated by Django 6.1 on 2026-09-01 12:59

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Your label for this credential, e.g. 'Salon Google account'.", max_length=120, unique=True)),
                ('auth_type', models.CharField(choices=[('service_account', 'Service account (JSON key)'), ('oauth', 'OAuth 2.0 (connected Google account)')], default='service_account', max_length=20)),
                ('service_account_json', models.TextField(blank=True, help_text='Paste the whole downloaded service-account JSON key file here.')),
                ('delegated_user', models.EmailField(blank=True, help_text='Google Workspace only: impersonate this user with domain-wide delegation. Leave empty for normal shared-calendar setups.', max_length=254)),
                ('oauth_client_id', models.CharField(blank=True, max_length=255)),
                ('oauth_client_secret', models.CharField(blank=True, max_length=255)),
                ('oauth_refresh_token', models.TextField(blank=True)),
                ('oauth_account_email', models.EmailField(blank=True, help_text='Filled in automatically after connecting.', max_length=254)),
                ('api_key', models.CharField(blank=True, help_text='Optional Google API key. Only usable for reading public calendars.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_check_result', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Google credential',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hair Salon', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Book your next appointment online', max_length=200)),
                ('about', models.TextField(blank=True, help_text='Shown on the homepage, plain text or simple HTML.')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, help_text='Shown to customers and used as reply-to.', max_length=254)),
                ('timezone_name', models.CharField(default='Europe/Berlin', help_text='IANA name, e.g. Europe/Berlin. All opening hours are interpreted in this zone.', max_length=64, verbose_name='time zone')),
                ('slot_interval_minutes', models.PositiveIntegerField(default=15, help_text='Appointments can start every N minutes.')),
                ('default_duration_minutes', models.PositiveIntegerField(default=45, help_text='Used when a calendar has no services attached.')),
                ('buffer_minutes', models.PositiveIntegerField(default=0, help_text='Cleaning / turnaround time kept free after every appointment.')),
                ('min_lead_time_hours', models.PositiveIntegerField(default=2, help_text='Customers cannot book anything starting sooner than this.')),
                ('max_advance_days', models.PositiveIntegerField(default=60, help_text='How far into the future the booking calendar goes.')),
                ('require_approval', models.BooleanField(default=True, help_text="On: bookings arrive as 'pending' and the calendar owner accepts or declines them by email. Off: bookings are confirmed immediately.")),
                ('respect_google_busy', models.BooleanField(default=True, help_text='Also hide slots that are busy in the linked Google Calendar (free/busy lookup).')),
                ('notify_email', models.EmailField(blank=True, help_text='Optional extra address that gets a copy of every booking notification.', max_length=254)),
                ('booking_terms', models.TextField(blank=True, help_text='Small print shown under the booking form (cancellation policy, etc.).')),
            ],
            options={
                'verbose_name': 'salon settings',
                'verbose_name_plural': 'salon settings',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Shown on the homepage, e.g. 'Maria - Colour & Cuts'.", max_length=120)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to auto-fill.', max_length=140, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short blurb shown on the calendar card.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='calendars/')),
                ('colour', models.CharField(default='#b0855b', help_text="Accent colour for this calendar's card (hex).", max_length=7)),
                ('google_calendar_id', models.CharField(help_text="The Google Calendar ID: 'primary', an address like name@gmail.com, or the long ...@group.calendar.google.com id from Calendar settings.", max_length=255)),
                ('owner_email', models.EmailField(help_text='The Google account that owns this calendar. Accept / decline emails go here.', max_length=254)),
                ('default_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Overrides the salon default for this calendar.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive calendars disappear from the homepage.')),
                ('accepts_online_booking', models.BooleanField(default=True, help_text='Show the calendar but turn its booking button off.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_error', models.TextField(blank=True, editable=False)),
                ('credential', models.ForeignKey(blank=True, help_text='Leave empty to keep this calendar local only (no Google sync).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendars', to='booking.googlecredential')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('calendars', models.ManyToManyField(blank=True, help_text='Leave empty to offer this service on every calendar.', related_name='services', to='booking.calendar')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, help_text="Shown to customers, e.g. 'Summer holiday'.", max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Inclusive: same date as start for a single day.')),
                ('all_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, help_text="Only when 'all day' is off.", null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('calendar', models.ForeignKey(blank=True, help_text='Leave empty to close the whole salon.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='booking.calendar')),
            ],
            options={
                'verbose_name': 'time off / vacation',
                'verbose_name_plural': 'time off / vacation',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_closed', models.BooleanField(default=False, help_text='Tick to close this weekday entirely.')),
                ('opens_at', models.TimeField(default=datetime.time(9, 0))),
                ('closes_at', models.TimeField(default=datetime.time(18, 0))),
                ('break_start', models.TimeField(blank=True, help_text='Optional lunch break start.', null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('calendar', models.ForeignKey(blank=True, help_text='Leave empty for the salon-wide default.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='booking.calendar')),
            ],
            options={
                'verbose_name': 'business hours',
                'verbose_name_plural': 'business hours',
                'ordering': ['calendar__sort_order', 'weekday'],
                'constraints': [models.UniqueConstraint(fields=('calendar', 'weekday'), name='unique_hours_per_calendar_weekday')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('decision_note', models.TextField(blank=True, help_text='Optional message sent to the customer.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('google_synced_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('google_sync_error', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.calendar')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.service')),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['calendar', 'start_at'], name='booking_app_calenda_48cedd_idx'), models.Index(fields=['status'], name='booking_app_status_513784_idx')],
            },
        ),
    ]
