# Generated by Django 6.1 on 2026-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text="Leave this empty and use the 'Create a new Google calendar' action: the credential makes the calendar itself, so nothing has to be set up inside a Google account. Otherwise paste an existing Calendar ID ('primary', name@gmail.com, or a ...@group.calendar.google.com id) and share that calendar with the credential.", max_length=255),
        ),
    ]
