# Generated by Django 6.1 on 2026-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_calendar_google_calendar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthClientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, help_text='Looks like 123456789-abc123.apps.googleusercontent.com', max_length=255, verbose_name='Google Client ID')),
                ('client_secret_encrypted', models.TextField(blank=True, editable=False, verbose_name='Google Client Secret')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google OAuth client',
                'verbose_name_plural': 'Google OAuth client',
            },
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='connected_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='oauth_access_token',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='oauth_scopes',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='oauth_token_expiry',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
