# Generated by Django 6.1 on 2026-09-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_googleoauthclientsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredential',
            name='is_default_sender',
            field=models.BooleanField(default=False, help_text='With several Google accounts connected, this is the one booking emails are sent from. Only one account can be the sender.', verbose_name='send salon email from this account'),
        ),
    ]
