# Generated by Django 6.1 on 2026-09-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_googlecredential_is_default_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_rsvp',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
